### ISSUE TITLE
Error with sprockets-rails v2.2.3

### ISSUE THREAD

**Issue by manuelmeurer** [bokmann/font-awesome-rails#124]
I just updated to sprockets-rails v2.2.3 (released today) and got the following error:

```
Sprockets::Rails::Helper::AssetFilteredError: Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( fontawesome-webfont.eot )` to `config/initializers/assets.rb` and restart your server
```

Once I do that, it asks me to add `fontawesome-webfont.woff` and so forth, for all files in https://github.com/bokmann/font-awesome-rails/tree/master/app/assets/fonts

I'm not sure what causes the error (maybe this? https://github.com/rails/sprockets-rails/commit/b52d19ff13f546c2afff2792b271289a9143454f).

How about adding all fonts to `Rails.application.config.assets.precompile` by default?

**Comment by jrodrigosm** [comment]
Same thing here.

**Comment by DaniG2k** [comment]
Same here. Posted an issue on [Stackoverflow](http://stackoverflow.com/questions/28092563/rails-4-fontawesome-causing-assetfilterederror)

**Comment by rmm5t** [comment]
Thanks for the report. 

> I just updated to sprockets-rails v2.2.3 (released today) and got the following error:

What version of sprockets-rails did you upgrade from?

Is there documentation or a discussion anywhere in sprockets-rails or sprockets that you can point to so that we can better understand their change in direction & defaults?

**Comment by manuelmeurer** [comment]
I updated from v2.2.2. See here for the changes: https://github.com/rails/sprockets-rails/compare/v2.2.2...v2.2.3
I'm pretty sure they didn't change anything on purpose where they know it would break existing libraries like this.

**Comment by acrogenesis** [comment]
same error here

**Comment by sankalpsingha** [comment]
Same error here!! Please advise!!

**Comment by sstarr** [comment]
Same here, I've rolled back to Sprockets 2.2.2 for now.

**Comment by rmm5t** [comment]
Since it happened between sprockets-rails 2.2.2 and 2.2.3, I guess I'm curious as to why you're opening a bug request here. Is this gem doing something wrong? [Semver](http://semver.org/) would suggest that the issue should be opened with sprockets-rails.

It sounds like sprockets-rails made a backwards incompatible change with regards to how font assets are picked up for precompile, no?  

I have no problem making a change here, but I just want to better understand the reasons behind the changes to the asset pipeline's behavior first. 

For everyone else, posting here with _"same error here"_ doesn't help anyone. Please provide docs or links to changed code or new docs. After all, freezing your project to sprockets-rails v2.2.2 shouldn't be that big of a deal for the time being.

**Comment by beneggett** [comment]
+1 same issue today

**Comment by jrodrigosm** [comment]
You are right. There's an open issue in sprockets-rails regarding this (https://github.com/rails/sprockets-rails/issues/217), it apparently affects other assets.

**Comment by manuelmeurer** [comment]
@rmm5t I opened a issue here because I thought the font-awesome-rails font files really needed to be added to the precompile list, and until now sprockets-rails hadn't checked that properly.
You're right of course, according to semver a change from 2.2.2 to 2.2.3 shouldn't brake anything.
Let's all direct our attention to https://github.com/rails/sprockets-rails/issues/217 and post "same error here"! :smile_cat:

**Comment by rmm5t** [comment]
FYI: sprockets-rails v2.2.4 should now fix this.

**Comment by csexton** [comment]
:heart: thanks for the quick update and release!
