### ISSUE TITLE
Query strings in font resource URLs break caching

### ISSUE THREAD

**Issue by abevoelker** [bokmann/font-awesome-rails#132]
I'm probably being a bit anal retentive in trying to maximize my site performance, but is there a reason that [the font URLs have a query string of `"?v=#{FontAwesome::Rails::FA_VERSION}"`](https://github.com/bokmann/font-awesome-rails/blob/159f76464e3a6cde081188d47eeeb6f45ab603f2/app/assets/stylesheets/font-awesome.css.erb#L15-L16) appended to them?  If it's for cache busting, wouldn't the asset pipeline digest URLs take care of that already?

![perf](https://cloud.githubusercontent.com/assets/153459/6181907/573408a0-b300-11e4-9030-60a259eea012.png)

Really awesome gem by the way, I really appreciate the work on it! :heart:

**Comment by rmm5t** [comment]
This won't affect your site performance at all.

You're correct that they shouldn't be necessary in a production environment
with asset pipeline digest URLs, but these extra cache busters remain for
two reasons:

1) The underlying CSS for font awesome core has them, and we simply match
that.

2) More importantly, in Rails 3.2 and in development mode, rails does not
include the digests for assets. We used to get a ridiculous amount of "bug
reports" because people didn't understand how and where caching was
happening in development. These cache busters help thwart those bogus
reports when people upgrade versions.

**Comment by abevoelker** [comment]
Understood, I figured there was a good reason!  And even if it did minutely hurt performance that's a sacrifice I'm willing to make for the convenience of the gem.

Thanks again for the gem!
