### ISSUE TITLE
 Sass::SyntaxError: Undefined variable: "$fa-css-prefix".

### ISSUE THREAD

**Issue by SurajShukla** [bokmann/font-awesome-rails#141]
Hello,

I am not sure If this is an issue, but I am struggling with it.  I have a theme with number of sliders being used in that along with bootstrap and font-awesome.

While I try to put the app on heroku, I get this error 

```
Sass::SyntaxError: Undefined variable: "$fa-css-prefix".
```

Here's this on [Stackoverflow](http://stackoverflow.com/questions/30885509/bundle-exec-rake-assetsprecompile-throws-font-awesome-related-issue)

Please check and let me know If I am missing something.

Thanks

**Comment by rmm5t** [comment]
font-awesome-rails does not depend on Sass. Your problem must be elsewhere.

**Comment by SurajShukla** [comment]
While i am using the gem, none of the fonts are loading for me.
I am not sure what the issue is.

I am simply adding the gem and requiring them in my application.css

**Comment by rmm5t** [comment]
@SurajShukla  When you submitted this Issue, GitHub prompted you to **first read our [Contribution Guidelines](https://github.com/bokmann/font-awesome-rails/blob/master/CONTRIBUTING.md)**.  We'd really appreciate it if you could do that first.

These guidelines provide good debugging steps that you should follow (often in general) before submitting an Issue here.

If you still have trouble after following all the steps, we can only help if you also submit the required bits of information that we ask for in those debugging steps.

This issue is closed, but feel free to submit more information and request that we re-open it if you feel that is warranted later.

**Comment by syedmahmad** [comment]
Hello EveryOne.
Just add these lines in your config/application.rb if you are using scss instead of css.

config.assets.precompile << %w( *.scss *.js )

**Comment by Tibzie** [comment]
I bumped into the same issue.

`Sass::SyntaxError:Undefined variable: "$fa-css-prefix".`

Apparently, as obvious as it may sound, scss stylesheet order matters.
As they (Fontawesome.com) say,
> Import Font Awesome by adding import "scss/fontawesome.scss" in your main SCSS file. Also, import **one or more styles** import "scss/solid.scss" in your main SCSS file.

I did the step below and it WORKED! ( you can comment the ones under the scss files, but make sure the ones with scss extensions stay on top. I hope it makes sense)
![scss order](https://user-images.githubusercontent.com/38702209/54711029-e4cad900-4b40-11e9-873f-df69ad2d9408.JPG)

Also, make sure you follow the official Fontawesome steps
[Adding Font Awesome to Your Compile](https://fontawesome.com/how-to-use/on-the-web/using-with/sass)
