### ISSUE TITLE
Icons not working in Internet Explorer 8

### ISSUE THREAD

**Issue by Corb3nik** [bokmann/font-awesome-rails#143]
Hey guys,

I can't get the icons to work on IE8. When I check developer tools, the CSS file that is generated contains [?] boxes instead of the icons/hex values.

![screen shot 2015-07-14 at 2 55 10 pm](https://cloud.githubusercontent.com/assets/6225588/8681980/8fc4f3aa-2a38-11e5-80a0-fe3fa96959c0.png)

EDIT: Just tried the your github website and I am getting similar results : 
![screen shot 2015-07-14 at 2 58 41 pm](https://cloud.githubusercontent.com/assets/6225588/8682071/f25372bc-2a38-11e5-9b21-e38b426e72be.png)

I am using Internet Explorer 8 Version 8.0.7601 on Windows 7

Do you guys support this browser?

**Comment by rmm5t** [comment]
> I can't get the icons to work on IE8.

Microsoft is officially ending support for IE8 in 6 months (Jan 2016). I'd argue that anyone else continuing to support IE8 in the meantime is wasting their time down the rabbit hole.
https://www.gartner.com/doc/2993017/microsoft-plans-end-support-windows
https://support.microsoft.com/en-us/lifecycle?p1=13418

> Just tried the your github website and I am getting similar results

That's now our site. We're just a asset gem on top of the [core FontAwesome](https://github.com/FortAwesome/Font-Awesome). If you want to get IE8 support on Windows 7, your best bet is to report the issue to them, but I would first [search their issues](https://github.com/FortAwesome/Font-Awesome/issues), because I'd guess that they've already addressed their support strategy for IE8.

However, with all that said, does this suggested workaround help?
https://thedesignspace.net/2014/01/19/ie8-and-fontawesome-fontface/#.VaV0NxNVhBc
