### ISSUE TITLE
undefined method `fa_icon' for #...

### ISSUE THREAD

**Issue by matheusvetor** [bokmann/font-awesome-rails#86]
Hi, i'm using the font-awesome-rails in my Rails Engine and show this error when i try to use the fa_icon helper in my layout: "undefined method `fa_icon' for #<#Class:0x00000102dff310:0x00000102a97b00>".
Rails Version: 4.0.4

**Comment by oniofchaos** [comment]
This worked for me too. I added `include FontAwesome::Rails::IconHelper` to `engine_name/app/helpers/engine_name/application_helper.rb`.

**Comment by itsmrwave** [comment]
This happens if you have `include_all_helpers` to `false`.

In previous versions of Rails the controller would include a helper whose name matches that of the controller, e.g., MyController will automatically include MyHelper. In Rails >= 3.1 helpers are available to all views, all the time. So some people set include_all_helpers config to false to return old behavior .

```ruby
config.action_controller.include_all_helpers = false
```

In the above case then adding `include FontAwesome::Rails::IconHelper` fixes the problem.
